server:
  port: 8081
spring:
  application:
    name: utils
  kafka:
    bootstrap-servers: localhost:9095
    consumer:
      enable-auto-commit: true
      group-id: group-demo-01
  secondKafka:
    bootstrap-servers: localhost:9096
    consumer:
      enable-auto-commit: true
      group-id: group-demo-02

logging:
  config: classpath:log4j2.xml