server:
  port: 8081
spring:
  application:
    name: utils
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      transaction-id-prefix: kafka_tx
      properties:
        enable.idempotence: true

    consumer:
      bootstrap-servers: localhost:9092

logging:
  config: classpath:log4j2.xml